MAKE="Various"
MODEL="12AX7"

GM_TEST_VA="250"
GM_CURRENT_GRID_MIN=-5
GM_CURRENT_PLATE_MA_MAX=3.5
GM_PLATE_MA_MAX=3.5
GM_TRANSCONDUCTANCE_MAX=2.8


RP_TEST_VG="-2"
RP_CURRENT_GRID_MIN=-6
RP_VA_MAX=400
RP_CURRENT_PLATE_MA_MAX=3.5
RP_PLATE_MA_MAX=3.5
RP_RESISTANCE_KOHM_MAX=140
