MAKE="Various"
MODEL="12by7a"

GM_TEST_VA="300"
GM_CURRENT_GRID_MIN=-6
GM_CURRENT_PLATE_MA_MAX=70
GM_PLATE_MA_MAX=50
GM_TRANSCONDUCTANCE_MAX=15


RP_TEST_VG="-3.2"
RP_CURRENT_GRID_MIN=-6
RP_VA_MAX=300
RP_CURRENT_PLATE_MA_MAX=25
RP_PLATE_MA_MAX=20
RP_RESISTANCE_KOHM_MAX=100
