MAKE="Raytheon"
MODEL="5751"

GM_TEST_VA="250"
GM_CURRENT_GRID_MIN=-6
GM_CURRENT_PLATE_MA_MAX=6
GM_PLATE_MA_MAX=2.8
GM_TRANSCONDUCTANCE_MAX=3.6


RP_TEST_VG="-2.5"
RP_VA_MAX=400
RP_CURRENT_GRID_MIN=-6
RP_CURRENT_PLATE_MA_MAX=6
RP_PLATE_MA_MAX=2.8
RP_RESISTANCE_KOHM_MAX=180
