MAKE="Various"
MODEL="5814"

GM_TEST_VA="250"
GM_CURRENT_GRID_MIN=-20
GM_CURRENT_PLATE_MA_MAX=35
GM_PLATE_MA_MAX=30
GM_TRANSCONDUCTANCE_MAX=4


RP_TEST_VG="-8.5"
RP_CURRENT_GRID_MIN=-6

RP_VA_MAX=375
RP_CURRENT_PLATE_MA_MAX=35
RP_PLATE_MA_MAX=30
RP_RESISTANCE_KOHM_MAX=20
