MAKE="Various"
MODEL="6201"

GM_TEST_VA="250"
GM_CURRENT_GRID_MIN=-6
GM_CURRENT_PLATE_MA_MAX=20
GM_PLATE_MA_MAX=15
GM_TRANSCONDUCTANCE_MAX=6


RP_TEST_VG="-2"
RP_CURRENT_GRID_MIN=-10
RP_VA_MAX=375
RP_CURRENT_PLATE_MA_MAX=20
RP_PLATE_MA_MAX=15
RP_RESISTANCE_KOHM_MAX=50
