MAKE="Various"
MODEL="6ak5"

GM_TEST_VA="180"
GM_CURRENT_GRID_MIN=-5
GM_CURRENT_PLATE_MA_MAX=25
GM_PLATE_MA_MAX=15
GM_TRANSCONDUCTANCE_MAX=7


RP_TEST_VG="-2"
RP_CURRENT_GRID_MIN=-5
RP_VA_MAX=180
RP_CURRENT_PLATE_MA_MAX=12
RP_PLATE_MA_MAX=2
RP_RESISTANCE_KOHM_MAX=600
