MAKE="Various"
MODEL="6P1P-EV"

GM_TEST_VA="250"
GM_CURRENT_GRID_MIN=-25
GM_CURRENT_PLATE_MA_MAX=120
GM_PLATE_MA_MAX=80
GM_TRANSCONDUCTANCE_MAX=6


RP_TEST_VG="-12.5"
RP_CURRENT_GRID_MIN=0
RP_VA_MAX=400
RP_CURRENT_PLATE_MA_MAX=15
RP_PLATE_MA_MAX=15
RP_RESISTANCE_KOHM_MAX=100
