MAKE="Various"
MODEL="el84"

GM_TEST_VA="250"
GM_CURRENT_GRID_MIN=-10
GM_CURRENT_PLATE_MA_MAX=120
GM_PLATE_MA_MAX=15
GM_TRANSCONDUCTANCE_MAX=50


RP_TEST_VG="-7.3"
RP_CURRENT_GRID_MIN=-10
RP_VA_MAX=300
RP_CURRENT_PLATE_MA_MAX=60
RP_PLATE_MA_MAX=60
RP_RESISTANCE_KOHM_MAX=10
